version: '3.7'
services:
  db:
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: demo
      POSTGRES_DB: demo
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Africa/Douala
      PGTZ: Africa/Douala
    ports:
      - 5454:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/
      - ./var:/var/www/var

  node:
    build:
      context: ./node/
    command: yarn run start
    working_dir: /app
    volumes:
      - ../src/main/frontend:/app
    ports:
      - 4200:4200

  typesense:
    restart: unless-stopped
    image: typesense/typesense:0.18.0
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: typesensekey
    ports:
      - 8108:8108
    volumes:
      - ./search-data:/data
